# =====================================================
# Project data displayed on the Projects page.
#
# This section automatically fetches project information from your GitHub repositories.
#
# ✔ The `id` field should be the exact repository name
#    (e.g., from: github.com/<your-username>/<repo-name>)
#
# ✔ The `displayName` field controls how the project name appears on the website.
# ✔ Set `previewImage` to `repo` to use the repository social preview image automatically.
# ✔ Set `previewImage` to `repo:<path/in/repo>` to use a specific image file from that repository.
#
# ✔ Use the `featured` field to control which projects appear on the homepage.
#    - featured: true  → shown on the homepage
#    - featured: false → shown only on the Projects page
# =====================================================

projects:
  items:
    - id: "LTU-RAI/InLiER" # name of your GitHub repository (from: github.com/<your-username>/<repo-name>)
      displayName: "InLiER"
      previewImage: /images/helipr.gif
      featured: true

    - id: "LTU-RAI/opt-key" # name of your GitHub repository (from: github.com/<your-username>/<repo-name>)
      displayName: "opt-key"
      previewImage: /images/kitti_00_msa_example.gif
      featured: true

    - id: "LTU-RAI/sga-dpcc" # name of your GitHub repository (from: github.com/<your-username>/<repo-name>)
      displayName: "sga-dpcc"
      previewImage: /images/decompressed.gif
      featured: false
    
    - id: "nstathou/hello-slam" # full repository id (owner/repo)
      displayName: "hello-slam" # name that will be displayed on the website
      previewImage: /images/particle_filter.gif # path to the preview image (can be a local file or a URL)
      featured: true
    
    - id: "LTU-RAI/FRAME" # name of your GitHub repository (from: github.com/<your-username>/<repo-name>)
      displayName: "FRAME"
      previewImage: /images/jfr23_overlapping.drawio.png
      featured: false