# =====================================================
# Website Configuration
# This section contains general information about your website.
# =====================================================

site:
  name: "Nikolaos Stathoulopoulos" # Your name or the name of your website
  repoUrl: "https://github.com/nstathou/nstathou.github.io"
  description: "Personal webpage"
  author: "Nikolaos Stathoulopoulos"
